// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  xqNormal: require('../Images/Icons/xq_normal.png'),
  xqSelected: require('../Images/Icons/xq_selected.png'),
  mddNormal: require('../Images/Icons/mdd_normal.png'),
  mddSelected: require('../Images/Icons/mdd_selected.png'),
  meNormal: require('../Images/Icons/me_normal.png'),
  meSelected: require('../Images/Icons/me_selected.png'),
  mddBanner: require('../Images/mdd_banner.jpg'),
  oz: require('../Images/Icons/oz_icon.png'),
  yz: require('../Images/Icons/yz_icon.png'),
  fz: require('../Images/Icons/fz_icon.png'),
  hot: require('../Images/Icons/hot_icon.png'),
  mgBg: require('../Images/mg_bg.png'),
  hw: require('../Images/Icons/hw_icon.png'),
  rm: require('../Images/Icons/rm_icon.png'),
  nv: require('../Images/Icons/nv_icon.png'),
  sw: require('../Images/Icons/sw_icon.png'),
  xqBanner: require('../Images/banner.jpg'),
  rmPic1: require('../Images/rm_pic1.jpg'),
  rmPic2: require('../Images/rm_pic2.jpg'),
  hwPic: require('../Images/hw_pic.jpg'),
  smrz: require('../Images/Icons/smrz_icon.png'),
  zhdj: require('../Images/Icons/zhdj_icon.png'),
  ddjl: require('../Images/Icons/ddjl_icon.png'),
  phone: require('../Images/Icons/phone_icon.png'),
  mm: require('../Images/Icons/mm_icon.png'),
  xinxi: require('../Images/Icons/xinxi_icon.png'),
  meBg: require('../Images/me_bg.jpg')
}

export default images
